Update test.yml

diff --git a/.jfrog-pipelines/test.yml b/.jfrog-pipelines/test.yml
--- a/.jfrog-pipelines/test.yml
+++ b/.jfrog-pipelines/test.yml
@@ -4,20 +4,160 @@
 #     configuration:
 #       sourceArtifactory: s_artifactory
 #       pattern: "test-automation-generic-local/test.txt"
+# template: true
+# valuesFilePath: ./values.yml
+# pipelines:
+#   - name:  {{ .Values.ServiceName }}_Multi_Tenancy
+#     steps:
+#       - name: EXT_S_SYC_AU_0007
+#         type: Bash
+#         # configuration:
+#           # targetPath: "test-automation-generic-local/EXT_S_SYC_AU_0007"
+#           # forceXrayScan: true
+#           # integrations:
+#           #   - name: s_artifactory
+#           # inputResources:
+#           #   - name: EXT_S_SYC_AU_0007_fileSpec2
+#         execution:
+#           onExecute:
+#             - echo hehe
+
 template: true
 valuesFilePath: ./values.yml
 pipelines:
-  - name:  {{ .Values.ServiceName }}_Multi_Tenancy
+{{ range $env := .Values.Environments }}
+{{ if or (eq "{{gitBranch}}" "master") (hasPrefix "{{ .Values.ConfigProject }}" "{{gitBranch}}") ($env.IsDev) }}
+  - name: {{ .Values.ServiceName }}_Multi_Tenancy_{{ $env.Name }}_Region_Release
+    configuration:
+      environmentVariables:
+        readOnly:
+          MT_CELL_TASK:
+            description: "Select Multi Tenancy Cell task"
+            default: "{{ .Values.DefaultApplication }}"
+            values:
+              - ""
+              {{ range $app := $.Values.Applications }}
+              - "{{ $app }}"
+              {{ end }}
+              {{ if $env.IsDev }}
+              - cell
+              {{ end }}
+            allowCustom: true
+          ACTION:
+            description: "Select action"
+            default: "deploy"
+            values:
+              - "deploy"
+              - "dryrun"
+              - "undeploy"
+            allowCustom: false
+          REGION:
+            description: "Select region"
+            default: "{{ $env.DefaultRegion }}"
+            values:
+              - "{{ $env.DefaultRegion }}"
+              {{ range $region := $env.AdditionalRegions }}
+              - "{{ $region }}"
+              {{ end }}
+            allowCustom: true
+          {{ if $env.IsDev }}
+          MT_DEV_CELL:
+            description: "Dev cell name, leave empty to use default"
+            default: ""
+          GROUP:
+            description: "[Mandatory] Select the Org group you belong to"
+            default: ARTIFACTORY
+            values:
+              - ARTIFACTORY
+            allowCustom: false
+          NODES:
+            description: "The environment will run on AMD Nodes by default. To run on ARM nodes, set NODES=ARM, ARM is only support on AWS"
+            default: "AMD"
+            values:
+              - "AMD"
+              - "ARM"
+            allowCustom: false
+          HPA:
+            description: "Enable HPA for MT Services. Optional"
+            default: "no"
+            values:
+              - "no"
+              - "yes"
+            allowCustom: false
+          CONFIG_BRANCH:
+            description: "{{ .Values.ServiceName }} config branch. If empty will use master"
+            default: "{{gitBranch}}"
+            values:
+              - ""
+            allowCustom: true
+          SAAS_CONFIGURATION_BRANCH:
+            description: "saas-configuration branch. If empty will use master"
+            default: ""
+            values:
+              - ""
+            allowCustom: true
+          {{ end }}
     steps:
-      - name: EXT_S_SYC_AU_0007
-        type: Bash
+      - name: trigger_mt_pipeline
+        type: TriggerPipeline
         # configuration:
-          # targetPath: "test-automation-generic-local/EXT_S_SYC_AU_0007"
-          # forceXrayScan: true
-          # integrations:
-          #   - name: s_artifactory
-          # inputResources:
-          #   - name: EXT_S_SYC_AU_0007_fileSpec2
+        #   integrations:
+        #     - name: devf_embedded_pipelines
+        #   projectKey: {{ $env.DevOpsProjectKey }}
+        #   pipelineName: Multi_Tenancy_Cell_{{ $env.Name }}_Region_Release_Pipe
+        #   stepName: step_1_prep_env
         execution:
-          onExecute:
-            - echo hehe
+          onStart:
+            # - |
+            #   if [ -z "${MT_CELL_TASK}" ] || [ -z "${REGION}" ]; then
+            #     echo "MT_CELL_TASK and REGION cannot be empty"
+            #     exit 1
+            #   fi
+            - echo "Triggering Multi_Tenancy_Cell_{{ $env.Name }}_Region_Release_Pipe"
+            - echo "${ACTION}ing ${MT_CELL_TASK} in region ${REGION}"
+            # - set_trigger_payload pipelineVariables "MT_CELL_TASK='${MT_CELL_TASK}'" "MT_DEV_CELL='${MT_DEV_CELL}'" "ACTION='${ACTION}'" "REGION='${REGION}'" "GROUP='${GROUP}'" "NODES='${NODES}'" "HPA='${HPA}'" "CONFIG_PROJECT='{{ .Values.ConfigProject }}'" "CONFIG_REPO='{{ .Values.ConfigRepo }}'" "CONFIG_BRANCH='${CONFIG_BRANCH}'" "SAAS_CONFIGURATION_BRANCH='${SAAS_CONFIGURATION_BRANCH}'"
+            # - export pipelines_poll_interval_seconds=5
+          onSuccess:
+            - echo "Successfully finished ${MT_CELL_TASK} ${ACTION} in region ${REGION}"
+          onFailure:
+            - echo "Failed ${MT_CELL_TASK} ${ACTION} in region ${REGION}"
+
+  - name: {{ .Values.ServiceName }}_Multi_Tenancy_{{ $env.Name }}_AllRegions_Release
+    configuration:
+      environmentVariables:
+        readOnly:
+          MT_CELL_TASK:
+            description: "Select Multi Tenancy Cell task"
+            default: "{{ .Values.DefaultApplication }}"
+            values:
+              - ""
+              {{ range $app := $.Values.Applications }}
+              - "{{ $app }}"
+              {{ end }}
+            allowCustom: true
+    steps:
+      - name: trigger_mt_pipeline
+        type: TriggerPipeline
+        # configuration:
+        #   integrations:
+        #     - name: devf_embedded_pipelines
+        #   projectKey: {{ $env.DevOpsProjectKey }}
+        #   pipelineName: Multi_Tenancy_Cell_{{ $env.Name }}_Release_Pipe
+        #   stepName: step_1_prep_env
+        execution:
+          onStart:
+            # - |
+            #   if [ -z "${MT_CELL_TASK}" ]; then
+            #     echo "MT_CELL_TASK cannot be empty"
+            #     exit 1
+            #   fi
+            - echo "Triggering Multi_Tenancy_Cell_{{ $env.Name }}_Release_Pipe"
+            - echo "deploying ${MT_CELL_TASK} in all regions"
+            # - set_trigger_payload pipelineVariables "MT_CELL_TASK='${MT_CELL_TASK}'" "CONFIG_PROJECT='{{ .Values.ConfigProject }}'" "CONFIG_REPO='{{ .Values.ConfigRepo }}'"
+            # - export pipelines_poll_interval_seconds=30
+          onSuccess:
+            - echo "Successfully finished ${MT_CELL_TASK} deploy"
+          onFailure:
+            - echo "Failed ${MT_CELL_TASK} deploy in all regions"
+{{ end }}
+{{ end }}
